//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.GetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interior
    {
        public int Id { get; set; }
        public string unit { get; set; }
        public string telephon { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string website { get; set; }
    }
}
